const data = {
  Januar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
  'Restabfall/0': ['Neujahr', null, null, '4', null, '2', null, null, null, null, '3', null, '1', null, null, null, null, '4', null, '2', null, null, null, null, '3', null, '1', null, null, null, null],
  'Bio-Tonne/0': ['Neujahr', null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null],
  'Blaue Tonne/0': ['Neujahr', null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null],
  'Gelbe Tonne / Gelber Sack/0': ['Neujahr', null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null],
  'Sperrgut/0': ['Neujahr', null, null, null, '1', '4', null, null, null, null, null, '2', '3', null, null, null, null, null, '1', '4', null, null, null, null, null, '2', '3', null, null, null, null],
  Weihnachtsbäume: ['Neujahr', null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, 'Alle', null, null, null, null, null, null, null, null, null, null],
  'Elektrogroßgeräte/0': ['Neujahr', null, null, null, null, '4', null, null, null, null, null, null, null, null, null, null, null, null, null, '3', null, null, null, null, null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/0': ['Neujahr', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null, null],
  Februar: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, null, null, null],
  'Restabfall/1': ['4', null, '2', null, null, null, null, '3', null, '1', null, null, null, null, '4', null, '2', null, null, null, null, '3', null, '1', null, null, null, 'Rosenmontag', null, null, null],
  'Bio-Tonne/1': [null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, 'Rosenmontag', null, null, null],
  'Blaue Tonne/1': [null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, 'Rosenmontag', null, null, null],
  'Gelbe Tonne / Gelber Sack/1': ['1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, 'Rosenmontag', null, null, null],
  'Sperrgut/1': [null, '1', '4', null, null, null, null, null, '2', '3', null, null, null, null, null, '1', '4', null, null, null, null, null, '2', '3', null, null, null, 'Rosenmontag', null, null, null],
  'Grünschnitt/1': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Rosenmontag', null, null, null],
  'Elektrogroßgeräte/1': [null, null, null, null, null, null, null, null, null, '1', null, null, null, null, null, null, null, null, null, null, null, null, null, '2', null, null, null, 'Rosenmontag', null, null, null],
  'Schadstoffe (Term. s. Seite 7)/1': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null, 'Rosenmontag', null, null, null],
  März: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
  'Restabfall/2': [4, null, 2, null, null, null, null, 3, null, 1, null, null, null, null, 4, null, 2, null, null, null, null, 3, null, 1, null, null, null, null, 4, null, 2],
  'Bio-Tonne/2': [null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null],
  'Blaue Tonne/2': [null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null],
  'Gelbe Tonne / Gelber Sack/2': [null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4'],
  'Sperrgut/2': [null, 1, 4, null, null, null, null, null, 2, 3, null, null, null, null, null, 1, 4, null, null, null, null, null, 2, 3, null, null, null, null, null, 1, 4],
  'Grünschnitt/2': [null, null, null, null, null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, null, null, null, null],
  'Elektrogroßgeräte/2': [null, null, 4, null, null, null, null, null, null, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/2': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null, null, null, null, null],
  April: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, null],
  'Restabfall/3': [null, null, null, null, '3', null, '1', null, null, null, null, '4', null, '2', 'Karfreitag', null, null, 'Ostermontag', null, '3', null, '1', null, null, null, '4', null, '2', null, null, null],
  'Bio-Tonne/3': [null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, 'Karfreitag', null, null, 'Ostermontag', '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null],
  'Blaue Tonne/3': [null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, 'Karfreitag', null, null, 'Ostermontag', null, null, '1+4', null, null, null, null, null, '2+3', null, null, null, null],
  'Gelbe Tonne / Gelber Sack/3': [null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, 'Karfreitag', null, null, 'Ostermontag', null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null],
  'Sperrgut/3': [null, null, null, null, null, '2', '3', null, null, null, null, null, '1', '4', 'Karfreitag', null, null, 'Ostermontag', null, '2', '3', null, null, null, null, null, '1', '4', null, null, null],
  'Grünschnitt/3': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Karfreitag', null, null, 'Ostermontag', null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null],
  'Elektrogroßgeräte/3': [null, null, null, null, null, null, '1', null, null, null, null, null, null, null, 'Karfreitag', null, null, 'Ostermontag', null, null, '2', null, null, null, null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/3': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Karfreitag', null, null, 'Ostermontag', null, null, 'A', null, 'B', null, null, null, null, null, null, null, null],
  Mai: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
  'Restabfall/4': ['Maifeiertag', null, '3', null, '1', null, null, null, null, '4', null, '2', null, null, null, null, '3', null, '1', null, null, null, null, '4', null, 'Christi Himmelfahrt', '2', null, null, null, '3'],
  'Bio-Tonne/4': ['Maifeiertag', '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, 'Christi Himmelfahrt', null, '2+3', null, '1+4', null],
  'Blaue Tonne/4': ['Maifeiertag', null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', 'Christi Himmelfahrt', null, null, null, null, null],
  'Gelbe Tonne / Gelber Sack/4': ['Maifeiertag', null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, 'Christi Himmelfahrt', '3+4', null, null, null, null],
  'Sperrgut/4': ['Maifeiertag', null, null, '2', '3', null, null, null, null, null, '1', '4', null, null, null, null, null, '2', '3', null, null, null, null, null, '1', 'Christi Himmelfahrt', '4', null, null, null, null],
  'Grünschnitt/4': ['Maifeiertag', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'Christi Himmelfahrt', null, null, null, null, null],
  'Elektrogroßgeräte/4': ['Maifeiertag', null, null, null, '4', null, null, null, null, null, null, null, null, null, null, null, null, null, '3', null, null, null, null, null, null, 'Christi Himmelfahrt', null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/4': ['Maifeiertag', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', 'Christi Himmelfahrt', null, 'B', null, null, null],
  Juni: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, null],
  'Restabfall/5': [null, '1', null, null, null, 'Pfingstmontag', null, '4', null, '2', null, null, null, '3', null, 'Fronleichnam', '1', null, null, null, '4', null, '2', null, null, null, null, '3', null, '1', null],
  'Bio-Tonne/5': [null, null, '2+3', null, null, 'Pfingstmontag', '1+4', null, null, null, '2+3', null, '1+4', null, null, 'Fronleichnam', null, '2+3', null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, null],
  'Blaue Tonne/5': ['1+4', null, null, null, null, 'Pfingstmontag', null, null, '2+3', null, null, null, null, null, '1+4', 'Fronleichnam', null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null],
  'Gelbe Tonne / Gelber Sack/5': [null, null, null, null, null, 'Pfingstmontag', null, '1+2', null, '3+4', null, null, null, null, null, 'Fronleichnam', null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null],
  'Sperrgut/5': ['2', '3', null, null, null, 'Pfingstmontag', null, '1', '4', null, null, null, null, null, '2', 'Fronleichnam', '3', null, null, null, null, '1', '4', null, null, null, null, null, '2', '3', null],
  'Grünschnitt/5': [null, null, null, null, null, 'Pfingstmontag', null, null, null, null, null, null, null, null, null, 'Fronleichnam', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  'Elektrogroßgeräte/5': [null, null, null, null, null, 'Pfingstmontag', null, null, '1', null, null, null, null, null, null, 'Fronleichnam', null, null, null, null, null, null, '2', null, null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/5': [null, null, null, null, null, 'Pfingstmontag', null, null, null, null, null, null, null, null, null, 'Fronleichnam', null, null, null, null, null, null, 'A', null, 'B', null, null, null, null, null, null],
  Juli: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
  'Restabfall/6': [null, null, null, null, 4, null, 2, null, null, null, null, 3, null, 1, null, null, null, null, 4, null, 2, null, null, null, null, 3, null, 1, null, null, null],
  'Bio-Tonne/6': ['2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null],
  'Blaue Tonne/6': [null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null],
  'Gelbe Tonne / Gelber Sack/6': [null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null],
  'Sperrgut/6': [null, null, null, null, null, 1, 4, null, null, null, null, null, 2, 3, null, null, null, null, null, 1, 4, null, null, null, null, null, 2, 3, null, null, null],
  'Grünschnitt/6': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  'Elektrogroßgeräte/6': [null, null, null, null, null, null, 4, null, null, null, null, null, null, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/6': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null],
  August: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
  'Restabfall/7': [null, 4, null, 2, null, null, null, null, 3, null, 1, null, null, null, null, 4, null, 2, null, null, null, null, 3, null, 1, null, null, null, null, 4, null],
  'Bio-Tonne/7': ['1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null],
  'Blaue Tonne/7': [null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3'],
  'Gelbe Tonne / Gelber Sack/7': [null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null],
  'Sperrgut/7': [null, null, 1, 4, null, null, null, null, null, 2, 3, null, null, null, null, null, 1, 4, null, null, null, null, null, 2, 3, null, null, null, null, null, 1],
  'Grünschnitt/7': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  'Elektrogroßgeräte/7': [null, null, null, 1, null, null, null, null, null, null, null, null, null, null, null, null, null, 2, null, null, null, null, null, null, null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/7': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null, null, null, null],
  September: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, null],
  'Restabfall/8': [2, null, null, null, null, 3, null, 1, null, null, null, null, 4, null, 2, null, null, null, null, 3, null, 1, null, null, null, null, 4, null, 2, null, null],
  'Bio-Tonne/8': [null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null, null, '1+4', null, null, null, '2+3', null],
  'Blaue Tonne/8': [null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null],
  'Gelbe Tonne / Gelber Sack/8': ['3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null],
  'Sperrgut/8': [4, null, null, null, null, null, 2, 3, null, null, null, null, null, 1, 4, null, null, null, null, null, 2, 3, null, null, null, null, null, 1, 4, null, null],
  'Grünschnitt/8': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null],
  'Elektrogroßgeräte/8': [null, null, null, null, null, null, null, 4, null, null, null, null, null, null, null, null, null, null, null, null, null, 3, null, null, null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/8': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null, null, null, null, null, null, null],
  Oktober: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
  'Restabfall/9': [null, null, 'Tag der deutschen Einheit', '3', null, '1', null, null, null, null, '4', null, '2', null, null, null, null, '3', null, '1', null, null, null, null, '4', null, '2', null, null, null, null],
  'Bio-Tonne/9': [null, null, 'Tag der deutschen Einheit', null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null],
  'Blaue Tonne/9': [null, null, 'Tag der deutschen Einheit', null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null],
  'Gelbe Tonne / Gelber Sack/9': [null, null, 'Tag der deutschen Einheit', null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null],
  'Sperrgut/9': [null, null, 'Tag der deutschen Einheit', null, '2', '3', null, null, null, null, null, '1', '4', null, null, null, null, null, '2', '3', null, null, null, null, null, '1', '4', null, null, null, null],
  'Grünschnitt/9': [null, null, 'Tag der deutschen Einheit', null, null, null, null, null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, null],
  'Elektrogroßgeräte/9': [null, null, 'Tag der deutschen Einheit', null, null, '1', null, null, null, null, null, null, null, null, null, null, null, null, null, '2', null, null, null, null, null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/9': [null, null, 'Tag der deutschen Einheit', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null, null],
  November: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, null],
  'Restabfall/10': ['Allerheiligen', '3', null, '1', null, null, null, '4', null, '2', null, null, null, null, '3', null, '1', null, null, null, null, '4', null, '2', null, null, null, null, '3', null, null],
  'Bio-Tonne/10': ['Allerheiligen', null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null],
  'Blaue Tonne/10': ['Allerheiligen', null, '1+4', null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null],
  'Gelbe Tonne / Gelber Sack/10': ['Allerheiligen', null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null],
  'Sperrgut/10': ['Allerheiligen', '2', '3', null, null, null, null, null, '1', '4', null, null, null, null, null, '2', '3', null, null, null, null, null, '1', '4', null, null, null, null, null, '2', null],
  'Grünschnitt/10': ['Allerheiligen', null, null, null, null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, null, null, null, null],
  'Elektrogroßgeräte/10': ['Allerheiligen', null, null, null, null, null, null, null, null, '4', null, null, null, null, null, null, null, null, null, null, null, null, null, '3', null, null, null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/10': ['Allerheiligen', null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null, null, null, null, null],
  Dezember: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
  'Restabfall/11': ['1', null, null, null, null, '4', null, '2', null, null, null, null, '3', null, '1', null, null, null, null, '4', null, '2', null, null, '1. Weihnachtstag', '2. Weihnachtstag', '3', null, '1', null, null],
  'Bio-Tonne/11': [null, null, null, null, '1+4', null, null, null, '2+3', null, null, null, null, null, null, null, null, null, '1+4', null, null, null, '2+3', null, '2. Weihnachtstag', '3. Weihnachtstag', null, null, null, null, null],
  'Blaue Tonne/11': [null, null, null, null, null, null, '2+3', null, null, null, null, null, null, '1+4', null, null, null, null, null, null, '2+3', null, null, null, '3. Weihnachtstag', '4. Weihnachtstag', null, '1+4', null, null, null],
  'Gelbe Tonne / Gelber Sack/11': [null, null, null, null, null, '1+2', null, '3+4', null, null, null, null, null, null, null, null, null, null, null, '1+2', null, '3+4', null, null, '4. Weihnachtstag', '5. Weihnachtstag', null, null, null, null, null],
  'Sperrgut/11': ['3', null, null, null, null, null, '1', '4', null, null, null, null, null, '2', '3', null, null, null, null, null, '1', '4', null, null, '5. Weihnachtstag', '6. Weihnachtstag', null, '2', '3', null, null],
  'Grünschnitt/11': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, '6. Weihnachtstag', '7. Weihnachtstag', null, null, null, null, null],
  'Elektrogroßgeräte/11': [null, null, null, null, null, null, null, '1', null, null, null, null, null, null, null, null, null, null, null, null, null, '2', null, null, '7. Weihnachtstag', '8. Weihnachtstag', null, null, null, null, null],
  'Schadstoffe (Term. s. Seite 7)/11': [null, null, null, null, null, null, null, null, null, null, null, null, null, null, 'A', null, 'B', null, null, null, null, null, null, null, '8. Weihnachtstag', '9. Weihnachtstag', null, null, null, null, null],
};
const monatMap = {
  0: '/0',
};
const bezirkMap = {
  1: 'Bezirk 1',
  2: 'Bezirk 2',
  3: 'Bezirk 4',
  4: 'Bezirk 4',
};

module.exports = {
  data,
  monatMap,
  bezirkMap,
};
